### ISSUE TITLE
Note: first board isn't built from template

### ISSUE THREAD

**Issue by mbbroberg** [bemosior/wardley-mapping-canvas#1]
Thank you so much for building this @bemosior (and introducing me to RealtimeBoard 😍). I ran through your readme and found the following behavior: 

* After sign up, I was launched into a new "blank" board
* When searching for templates inside the board, I didn't find a way to edit the template
* I then jumped back to my dashboard and found clicking "Blank board" showed me available templates
* I then searched and found yours

Given that behavior, I might offer a heads up in the readme for new users since it took me a little bit to realize I was in the wrong area. 

For reference, the search dialogue pops it right up! 

<img width="1086" alt="screen shot 2018-10-18 at 10 54 14 pm" src="https://user-images.githubusercontent.com/1744971/47197020-4c2df400-d329-11e8-9b91-bc95931f682b.png">

Thank you again for this awesome tutorial and setup! You rock 🤘

**Comment by bemosior** [comment]
Thank you so much for helping clarify the README! I'll take a look at the PR right away.
